apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://eddie-prometheus:9090
    isDefault: true
    editable: true
  
  - name: Bus API
    type: json
    access: proxy
    url: http://host.docker.internal:8503/communication
    jsonData:
      queryTimeout: 30s
    editable: true
