global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'agent-network-exporter'
    static_configs:
      - targets: ['agent-exporter-bridge:9101']
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'autocoinbot-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['172.17.0.1:9092']
        labels:
          coin: 'BTC-USDT'
          instance: 'btc_usdt'

  - job_name: 'crypto-exporter-eth_usdt'
    scrape_interval: 30s
    static_configs:
      - targets: ['172.17.0.1:9098']
        labels:
          coin: 'ETH-USDT'
          instance: 'eth_usdt'

  - job_name: 'crypto-exporter-xrp_usdt'
    scrape_interval: 30s
    static_configs:
      - targets: ['172.17.0.1:9094']
        labels:
          coin: 'XRP-USDT'
          instance: 'xrp_usdt'

  - job_name: 'crypto-exporter-sol_usdt'
    scrape_interval: 30s
    static_configs:
      - targets: ['172.17.0.1:9095']
        labels:
          coin: 'SOL-USDT'
          instance: 'sol_usdt'

  - job_name: 'crypto-exporter-doge_usdt'
    scrape_interval: 30s
    static_configs:
      - targets: ['172.17.0.1:9096']
        labels:
          coin: 'DOGE-USDT'
          instance: 'doge_usdt'

  - job_name: 'crypto-exporter-ada_usdt'
    scrape_interval: 30s
    static_configs:
      - targets: ['172.17.0.1:9097']
        labels:
          coin: 'ADA-USDT'
          instance: 'ada_usdt'
