apiVersion: 1

providers:
  - name: 'Prometheus'
    orgId: 1
    folder: ''
    type: file
    disableDeletion: false
    editable: true
    options:
      path: /etc/grafana/provisioning/datasources

datasources:
  - name: 'Prometheus'
    type: 'prometheus'
    access: 'proxy'
    orgId: 1
    url: 'http://192.168.15.2:9090'
    password: ''
    user: ''
    database: ''
    basicAuth: false
    isDefault: true
    jsonData:
      timeInterval: '15s'
    readOnly: false
  
  - name: 'PostgreSQL'
    type: 'postgres'
    access: 'proxy'
    orgId: 1
    url: 'eddie-postgres:5432'
    password: 'postgres'
    user: 'postgres'
    database: 'eddie_db'
    basicAuth: false
    isDefault: false
    jsonData:
      sslmode: 'disable'
    readOnly: false
