apiVersion: 1

datasources:
  - name: 'Prometheus'
    type: 'prometheus'
    access: 'proxy'
    orgId: 1
    url: 'http://192.168.15.2:9090'
    basicAuth: false
    isDefault: true
    jsonData:
      timeInterval: '15s'
    readOnly: false
